### ISSUE TITLE
请求支持Folia端！

### ISSUE THREAD

**Issue by x1aoren** [crackun24/TheStarryMiningList#12]
### Motivation

请求支持Folia端！
Folia目前也很流行！
恳请作者大大能实现我的愿望
这里有我的报错日志
[22:55:08 ERROR]: [DirectoryProviderSource] Error preparing plugin context: Directory 'plugins\TheStarryMiningList-mc1.20.6-v1.3.5.jar' failed to update!
java.lang.RuntimeException: Directory 'plugins\TheStarryMiningList-mc1.20.6-v1.3.5.jar' failed to update!
        at io.papermc.paper.plugin.provider.source.FileProviderSource.prepareContext(FileProviderSource.java:57) ~[luminol-1.20.6.jar:1.20.6-DEV-e991f0b]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.lambda$prepareContext$1(DirectoryProviderSource.java:33) ~[luminol-1.20.6.jar:1.20.6-DEV-e991f0b]
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:?]
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.walkFiles(DirectoryProviderSource.java:64) ~[luminol-1.20.6.jar:1.20.6-DEV-e991f0b]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.prepareContext(DirectoryProviderSource.java:31) ~[luminol-1.20.6.jar:1.20.6-DEV-e991f0b]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.prepareContext(DirectoryProviderSource.java:17) ~[luminol-1.20.6.jar:1.20.6-DEV-e991f0b]
        at io.papermc.paper.plugin.util.EntrypointUtil.registerProvidersFromSource(EntrypointUtil.java:14) ~[luminol-1.20.6.jar:1.20.6-DEV-e991f0b]
        at io.papermc.paper.plugin.PluginInitializerManager.load(PluginInitializerManager.java:109) ~[luminol-1.20.6.jar:1.20.6-DEV-e991f0b]
        at net.minecraft.server.Main.main(Main.java:122) ~[luminol-1.20.6.jar:1.20.6-DEV-e991f0b]
        at org.bukkit.craftbukkit.Main.main(Main.java:328) ~[luminol-1.20.6.jar:1.20.6-DEV-e991f0b]
        at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: org.bukkit.plugin.InvalidPluginException: java.lang.IllegalArgumentException: plugins\TheStarryMiningList-mc1.20.6-v1.3.5.jar does not contain a paper-plugin.yml or plugin.yml! Could not determine plugin type, cannot load a plugin from it!
        at io.papermc.paper.plugin.provider.source.FileProviderSource.checkUpdate(FileProviderSource.java:120) ~[luminol-1.20.6.jar:1.20.6-DEV-e991f0b]
        at io.papermc.paper.plugin.provider.source.FileProviderSource.prepareContext(FileProviderSource.java:55) ~[luminol-1.20.6.jar:1.20.6-DEV-e991f0b]
        ... 21 more
Caused by: java.lang.IllegalArgumentException: plugins\TheStarryMiningList-mc1.20.6-v1.3.5.jar does not contain a paper-plugin.yml or plugin.yml! Could not determine plugin type, cannot load a plugin from it!
        at io.papermc.paper.plugin.provider.source.FileProviderSource.getPluginName(FileProviderSource.java:129) ~[luminol-1.20.6.jar:1.20.6-DEV-e991f0b]
        at io.papermc.paper.plugin.provider.source.FileProviderSource.checkUpdate(FileProviderSource.java:101) ~[luminol-1.20.6.jar:1.20.6-DEV-e991f0b]
        at io.papermc.paper.plugin.provider.source.FileProviderSource.prepareContext(FileProviderSource.java:55) ~[luminol-1.20.6.jar:1.20.6-DEV-e991f0b]
        ... 21 more

### Description

请求支持Folia端！
Folia目前也很流行！
恳请作者大大能实现我的愿望
这里有我的报错日志
[22:55:08 ERROR]: [DirectoryProviderSource] Error preparing plugin context: Directory 'plugins\TheStarryMiningList-mc1.20.6-v1.3.5.jar' failed to update!
java.lang.RuntimeException: Directory 'plugins\TheStarryMiningList-mc1.20.6-v1.3.5.jar' failed to update!
        at io.papermc.paper.plugin.provider.source.FileProviderSource.prepareContext(FileProviderSource.java:57) ~[luminol-1.20.6.jar:1.20.6-DEV-e991f0b]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.lambda$prepareContext$1(DirectoryProviderSource.java:33) ~[luminol-1.20.6.jar:1.20.6-DEV-e991f0b]
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:?]
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.walkFiles(DirectoryProviderSource.java:64) ~[luminol-1.20.6.jar:1.20.6-DEV-e991f0b]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.prepareContext(DirectoryProviderSource.java:31) ~[luminol-1.20.6.jar:1.20.6-DEV-e991f0b]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.prepareContext(DirectoryProviderSource.java:17) ~[luminol-1.20.6.jar:1.20.6-DEV-e991f0b]
        at io.papermc.paper.plugin.util.EntrypointUtil.registerProvidersFromSource(EntrypointUtil.java:14) ~[luminol-1.20.6.jar:1.20.6-DEV-e991f0b]
        at io.papermc.paper.plugin.PluginInitializerManager.load(PluginInitializerManager.java:109) ~[luminol-1.20.6.jar:1.20.6-DEV-e991f0b]
        at net.minecraft.server.Main.main(Main.java:122) ~[luminol-1.20.6.jar:1.20.6-DEV-e991f0b]
        at org.bukkit.craftbukkit.Main.main(Main.java:328) ~[luminol-1.20.6.jar:1.20.6-DEV-e991f0b]
        at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: org.bukkit.plugin.InvalidPluginException: java.lang.IllegalArgumentException: plugins\TheStarryMiningList-mc1.20.6-v1.3.5.jar does not contain a paper-plugin.yml or plugin.yml! Could not determine plugin type, cannot load a plugin from it!
        at io.papermc.paper.plugin.provider.source.FileProviderSource.checkUpdate(FileProviderSource.java:120) ~[luminol-1.20.6.jar:1.20.6-DEV-e991f0b]
        at io.papermc.paper.plugin.provider.source.FileProviderSource.prepareContext(FileProviderSource.java:55) ~[luminol-1.20.6.jar:1.20.6-DEV-e991f0b]
        ... 21 more
Caused by: java.lang.IllegalArgumentException: plugins\TheStarryMiningList-mc1.20.6-v1.3.5.jar does not contain a paper-plugin.yml or plugin.yml! Could not determine plugin type, cannot load a plugin from it!
        at io.papermc.paper.plugin.provider.source.FileProviderSource.getPluginName(FileProviderSource.java:129) ~[luminol-1.20.6.jar:1.20.6-DEV-e991f0b]
        at io.papermc.paper.plugin.provider.source.FileProviderSource.checkUpdate(FileProviderSource.java:101) ~[luminol-1.20.6.jar:1.20.6-DEV-e991f0b]
        at io.papermc.paper.plugin.provider.source.FileProviderSource.prepareContext(FileProviderSource.java:55) ~[luminol-1.20.6.jar:1.20.6-DEV-e991f0b]
        ... 21 more

### Other information

请求支持Folia端！
Folia目前也很流行！
恳请作者大大能实现我的愿望
这里有我的报错日志
[22:55:08 ERROR]: [DirectoryProviderSource] Error preparing plugin context: Directory 'plugins\TheStarryMiningList-mc1.20.6-v1.3.5.jar' failed to update!
java.lang.RuntimeException: Directory 'plugins\TheStarryMiningList-mc1.20.6-v1.3.5.jar' failed to update!
        at io.papermc.paper.plugin.provider.source.FileProviderSource.prepareContext(FileProviderSource.java:57) ~[luminol-1.20.6.jar:1.20.6-DEV-e991f0b]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.lambda$prepareContext$1(DirectoryProviderSource.java:33) ~[luminol-1.20.6.jar:1.20.6-DEV-e991f0b]
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:?]
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.walkFiles(DirectoryProviderSource.java:64) ~[luminol-1.20.6.jar:1.20.6-DEV-e991f0b]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.prepareContext(DirectoryProviderSource.java:31) ~[luminol-1.20.6.jar:1.20.6-DEV-e991f0b]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.prepareContext(DirectoryProviderSource.java:17) ~[luminol-1.20.6.jar:1.20.6-DEV-e991f0b]
        at io.papermc.paper.plugin.util.EntrypointUtil.registerProvidersFromSource(EntrypointUtil.java:14) ~[luminol-1.20.6.jar:1.20.6-DEV-e991f0b]
        at io.papermc.paper.plugin.PluginInitializerManager.load(PluginInitializerManager.java:109) ~[luminol-1.20.6.jar:1.20.6-DEV-e991f0b]
        at net.minecraft.server.Main.main(Main.java:122) ~[luminol-1.20.6.jar:1.20.6-DEV-e991f0b]
        at org.bukkit.craftbukkit.Main.main(Main.java:328) ~[luminol-1.20.6.jar:1.20.6-DEV-e991f0b]
        at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: org.bukkit.plugin.InvalidPluginException: java.lang.IllegalArgumentException: plugins\TheStarryMiningList-mc1.20.6-v1.3.5.jar does not contain a paper-plugin.yml or plugin.yml! Could not determine plugin type, cannot load a plugin from it!
        at io.papermc.paper.plugin.provider.source.FileProviderSource.checkUpdate(FileProviderSource.java:120) ~[luminol-1.20.6.jar:1.20.6-DEV-e991f0b]
        at io.papermc.paper.plugin.provider.source.FileProviderSource.prepareContext(FileProviderSource.java:55) ~[luminol-1.20.6.jar:1.20.6-DEV-e991f0b]
        ... 21 more
Caused by: java.lang.IllegalArgumentException: plugins\TheStarryMiningList-mc1.20.6-v1.3.5.jar does not contain a paper-plugin.yml or plugin.yml! Could not determine plugin type, cannot load a plugin from it!
        at io.papermc.paper.plugin.provider.source.FileProviderSource.getPluginName(FileProviderSource.java:129) ~[luminol-1.20.6.jar:1.20.6-DEV-e991f0b]
        at io.papermc.paper.plugin.provider.source.FileProviderSource.checkUpdate(FileProviderSource.java:101) ~[luminol-1.20.6.jar:1.20.6-DEV-e991f0b]
        at io.papermc.paper.plugin.provider.source.FileProviderSource.prepareContext(FileProviderSource.java:55) ~[luminol-1.20.6.jar:1.20.6-DEV-e991f0b]
        ... 21 more

**Comment by x1aoren** [comment]
不好意思，没看清就来用了，有点着急
